name: build template

on:
  push:
    branches:
      - 'master'
      - '152-build-on-github-actions'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install vagrant and virtualbox
      run: |
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo openssl rand -out /var/lib/shim-signed/mok/.rnd -hex 256
        sudo apt update
        sudo apt install vagrant virtualbox virtualbox-guest-additions-iso

    - name: print versions and install plugin
      run: |
        vagrant --version
        vboxmanage --version
        vagrant plugin install vagrant-disksize

    - name: vagrant up
      env:
        VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}
        GITHUB_KEY: ${{ secrets.GITHUB_TOKEN }}
      run: vagrant up

    - name: vagrant halt
      run: vagrant halt
